version: '3.1'

services:

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wpadmin
      WORDPRESS_DB_PASSWORD: 12345678
      WORDPRESS_DB_NAME: wp
    volumes:
      - wordpress:/var/www/html

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: wp
      MYSQL_USER: wpadmin
      MYSQL_PASSWORD: 12345678
      MYSQL_ROOT_PASSWORD: 12345678
    volumes:
      - db:/var/lib/mysql
volumes:
  wordpress:
  db: